### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by ifq** [astaxie/weixin#3]
提示 `main.go:5:2: cannot find package "weixin/controllers" in any of` 
请问要怎么设置还是怎么的？

我通过 `go get github.com/astaxie/weixin` 命令获取的代码。
在代码根目录下 go install 失败。

**Comment by astaxie** [comment]
这个需要你把源码直接放在$gopath/src下面 不能通过go get获取，直接把源码放这个目录

**Comment by ifq** [comment]
谢谢啊。是我搞错了。
